---
- name: reboot
  hosts: all
  become: yes
  tasks:
    - name: if kernel is updated, reboot
      reboot:
      msg: "rebooting the system to apply the new kernel"
      reboot_timeout: 300
      pre_reboot_delay: 0
    - name: wait for hosts to come back online
      wait_for_connection: 
      delay: 30
      timeout: 300